name: Sample Evaluate Action
on:
  workflow_call:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  evaluate:
    runs-on: ubuntu-latest
    env:
      GENAI_EVALS_CONFIG_PATH: ${{ github.workspace }}/evaluate-config.json
      GENAI_EVALS_DATA_PATH: ${{ github.workspace }}/.github/.test_files/eval-input.jsonl
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.OIDC_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.OIDC_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.OIDC_AZURE_SUBSCRIPTION_ID }}

      - name: Write evaluate config (Python)
        env:
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_CHAT_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_CHAT_DEPLOYMENT }}
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION }}
        run: |
          python - <<'PY'
          import json, os, pathlib
          cfg = {
            "data": os.environ["GENAI_EVALS_DATA_PATH"],
            "evaluators": {
              "coherence": "CoherenceEvaluator",
              "fluency": "FluencyEvaluator"
            },
            "ai_model_configuration": {
              "type": "azure_openai",
              "azure_endpoint": os.environ["AZURE_OPENAI_ENDPOINT"],
              "azure_deployment": os.environ["AZURE_OPENAI_CHAT_DEPLOYMENT"],
              "api_key": os.environ["AZURE_OPENAI_API_KEY"],
              "api_version": os.environ["AZURE_OPENAI_API_VERSION"]
            }
          }
          p = pathlib.Path(os.environ["GENAI_EVALS_CONFIG_PATH"])
          p.write_text(json.dumps(cfg, indent=2), encoding="utf-8")
          print("Wrote", p, "OK")
          PY

      - name: (Optional) Validate config JSON
        run: |
          python - <<'PY'
          import json, pathlib, os
          p = pathlib.Path(os.environ["GENAI_EVALS_CONFIG_PATH"])
          json.loads(p.read_text(encoding="utf-8"))
          print("JSON valid:", p)
          PY

      - name: Run AI Evaluation
        id: run-ai-evaluation
        uses: microsoft/genai-evals@main
        with:
          evaluate-configuration: ${{ env.GENAI_EVALS_CONFIG_PATH }}
