name: Run Simulator-Evaluator (Automated yaml)

on:
  push:
  pull_request:

jobs:
  run-python:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   # REQUIRED for OIDC
      contents: read

    env:
      # your existing OpenAI envs (provided as repo secrets)
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT_NEW }}
      AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY_NEW }}
      AZURE_OPENAI_API_VERSION: ${{ secrets.AZURE_OPENAI_API_VERSION_NEW }}
      AZURE_OPENAI_CHAT_DEPLOYMENT: ${{ secrets.AZURE_OPENAI_CHAT_DEPLOYMENT_NEW }}
      # prevent interactive prompts on CI
      AZURE_IDENTITY_ENABLE_INTERACTIVE: "0"

    steps:
      - uses: actions/checkout@v4

      # OIDC login: NO client secret needed
      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.OIDC_AZURE_CLIENT_ID }}     # App registration's Application (client) ID
          tenant-id: ${{ secrets.OIDC_AZURE_TENANT_ID }}     # Directory (tenant) ID
          subscription-id: ${{ secrets.OIDC_AZURE_SUBSCRIPTION_ID }}

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Python
        run: python AdversarialSimulators/Simulate_Adversarial_Evaluate_Agent.py 2>&1 | tee logs/output.log

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: full-job-output
          path: full_output.log

